// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box2': string;
  'foo': string;
}
export const cssExports: CssExports;
export default cssExports;
